Repository crew-play/BackEnd, pull requests merged in 2024-12, with the labels that each got.

#57 [feat] 주제(CustomTopic) 조회 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/CustomTopicController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/CustomTopicService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/topic/CustomTopicResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRepository.java
Labels: enhancement

#60 [feat] 경기 일정 조회 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/FixtureHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SupportedClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/crawl/CrawlFixtures.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/FixturesController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/FixturesService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/FixturesServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Fixtures.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/FixturesRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SupportedClubsRepository.java
Labels: enhancement

#64 [feat] AWS S3 환경 세팅 및 이미지 업로드 로직 구현
  sport_companion/module-api/build.gradle
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/S3Handler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/S3Config.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
Labels: enhancement

#62 [feat] 주제(CustomTopic) 추천 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicRecommendHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/CustomTopicController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/CustomTopicService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/CustomTopicRecommendEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/topic/RecommendCountResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/RedisKeyType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRecommendRepository.java
Labels: enhancement

#67 [feat] 구단 등록 API 구현 및 List 반환 데이터 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/ClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/ReservationSiteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/S3Handler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SportHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/S3Config.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/club/ClubDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/clubs/Clubs.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/ReservationSiteRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SportRepository.java
Labels: enhancement, refactor

#66 [fix] 주제 추천수 조회 방식 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicRecommendHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/topic/CustomTopicResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/topic/TopicAndRecommendDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRecommendRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRepository.java
Labels: fix

#68 [feat] 투표 등록,수정,삭제 기능 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CandidateHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/VoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/VoteController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/VoteService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/CandidateEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/UserVoteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/VoteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/vote/CreateVoteDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CandidateRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UserVoteRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/VoteRepository.java
Labels: enhancement

#76 [feat] 선호구단 조회, 등록, 삭제 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SupportedClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/SupportClubController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/SupportClubService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/SupportClubServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/support/SupportClub.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SupportedClubsRepository.java
Labels: enhancement

#79 [feat] 사용자 투표하기 기능 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserVoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/VoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/VoteController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/VoteService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/VoteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/vote/CheckVotedResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UserVoteRepository.java
Labels: enhancement

#83 [feat] API 테스트 코드 작성
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/ReservationSiteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SupportedClubsHandler.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/ClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/FixtureHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/ReservationSiteHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/SportHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/SupportedClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/crawl/CrawlFixturesTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/FixturesServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/SupportClubServiceImplTest.java
Labels: enhancement

#84 [feat] 투표 결과 응답에 id, myVote 추가
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserVoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/vote/VoteResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UserVoteRepository.java
Labels: enhancement

#87 [fix] 투표 결과 조회 API 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/VoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/VoteController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/VoteService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SortType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/VoteRepository.java
Labels: enhancement

#90 [refactor] 코드 중간 리펙토링 작업
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SeasonHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/FixtureHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ReservationSiteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/SportHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/SupportedClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/crawl/CrawlFixtures.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/FixturesController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/SupportClubController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/UsersController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/FixturesService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/SupportClubService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/UsersService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/FixturesServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/SupportClubServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/UsersServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/SeasonHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/ClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/FixtureHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/ReservationSiteHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/SportHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/SupportedClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/crawl/CrawlFixturesTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/FixturesServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/SupportClubServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/FixturesEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SeasonsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Fixtures.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/FixturesRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SeasonsRepository.java
Labels: refactor

#99 [fix] vote, topic 관련 API 허용 권한 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
Labels: fix

#103 [feat] 투표 및 주제 응답 값 추가
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicRecommendHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/VoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/VoteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/topic/CustomTopicResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/vote/VoteResponse.java
Labels: enhancement

#105 [refactor] 중간 리펙토링 작업
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtUtil.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/oauth/KakaoAuthHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ClubsFacade.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/FixtureHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ReservationSiteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/RestaurantHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/SportHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/SupportedClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/TipsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/crawl/CrawlFixtures.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/topic/CustomTopicHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/topic/CustomTopicRecommendHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/vote/CandidateHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/vote/UserVoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/vote/VoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/SupportClubController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/SupportClubService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/FixturesServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/SupportClubServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/ClubsFacadeTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/ClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/FixtureHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/ReservationSiteHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/SportHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/club/SupportedClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/crawl/CrawlFixturesTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/FixturesServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/SupportClubServiceImplTest.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/NewsItemWriter.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/ClubsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/GameResultEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/PlayersEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/ReservationSiteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SportsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/auth/SignUpDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/club/ClubDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/PageResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/clubs/Clubs.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Fixtures.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Restaurant.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Tips.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/GameResultRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/PlayersRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/ReservationSiteRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SportRepository.java
Labels: refactor

#104 [feat] 회원 탈퇴 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/oauth/KakaoAuthHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRecommendRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SupportedClubsRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UserVoteRepository.java
Labels: enhancement

#98 [feat] 마이페이지 투표 주제 기능 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/topic/CustomTopicHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/CustomTopicController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/CustomTopicService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/CustomTopicEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRepository.java
Labels: enhancement

#107 [chore] Yml 파일 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/oauth/KakaoAuthHandler.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
  sport_companion/module-batch/src/main/resources/application-dev.yml
  sport_companion/module-batch/src/main/resources/application-prod.yml
Labels: refactor

#112 [feat] 구단 별 경기 일정 조회 메서드 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtUtil.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ClubsFacade.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/FixturesController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/FixturesService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/FixturesServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/FixturesRepository.java
Labels: enhancement

#110 [fix] WebDriver 빈대신 메서드로 생성
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/crawl/CrawlFixtures.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/MbcNewsCrawling.java
  sport_companion/module-core/src/main/java/com/service/sport_companion/core/component/WebDriverHandler.java
Labels: fix

#114 [feat] 이번주 투표 API 조회 방식 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/vote/UserVoteHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/VoteController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/VoteService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/VoteServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/vote/VoteResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/VoteResultType.java
Labels: enhancement

#117 [fix] 투표하기 권한 사용자 허용
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
Labels: bug, fix

#121 [refactor] 마이페이지 : 회원정보 조회, 선호구단 조회 API 병합처리
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/UsersServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/user/UserInfo.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
Labels: refactor

#119 [fix] 크롤링 스케줄링 timezone 설정
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/component/BatchScheduler.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/MbcNewsCrawling.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/news/NewsResponseDto.java
Labels: fix

#124 회원가입 선호구단 등록 및 마이페이지 사용자 정보 요청, 전달 방식 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/UsersServiceImpl.java
Labels: fix

#122 [Feat] 기능 별 테스트 코드 추가 및 수정
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/FixturesServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/UsersServiceImplTest.java
Labels: refactor

#128 [fix] 배치 작업 오류 수정을 위한 @JobScope 및 로그 추가
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/component/BatchScheduler.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/config/NewsCrawlConfig.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/MbcNewsCrawling.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/NewsItemWriter.java
Labels: bug, fix

#130 [feat] 경기 상세 정보 경기 일정 정보 추가
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/club/ClubsFacade.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/FixtureDetails.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/fixtures/Fixtures.java
Labels: enhancement
