Repository crew-play/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#2 [chore] build.gradle 수정
  subscription/build.gradle
Labels: fix

#6 [feat] Entity 클래스 및 Repository 클래스 구현
  sport_companion/module-core/src/main/java/com/service/sport_companion/core/config/JpaConfig.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/ClubsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/FixturesEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/GameResultEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/NewsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/PlayersEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SportsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SupportedClubsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/UsersEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UserRole.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/ClubsRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/FixturesRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/GameResultRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/NewsRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/PlayersRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SportRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SupportedClubsRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UsersRepository.java
Labels: enhancement

#8 [feat] Docker 설정을 위한 docker-compose, Dockerfile 파일 추가
  sport_companion/.gitignore
  sport_companion/Dockerfile
  sport_companion/docker-compose.yml
Labels: enhancement

#11 [feat] Swagger 도입
  sport_companion/module-api/build.gradle
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SwaggerConfig.java
Labels: enhancement

#12 [feat] OAuth2 카카오 로그인 및 회원가입 여부 검증 API 구현
  .gitignore
  docker-compose.yml
  sport_companion/.gitignore
  sport_companion/Dockerfile
  sport_companion/module-api/build.gradle
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtUtil.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/nickname/NicknameHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/oauth/KakaoAuthHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SwaggerConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/UserDetailServiceImpl.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
  sport_companion/module-api/src/main/resources/application.yml
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/UserHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-core/src/main/java/com/service/sport_companion/core/exception/GlobalException.java
  sport_companion/module-core/src/main/java/com/service/sport_companion/core/exception/GlobalExceptionHandler.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/UsersEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/auth/KakaoUserDetailsDTO.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/ResultResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/TokenType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/UsersRepository.java
Labels: enhancement

#16 [chore] docker-compose.yml npm 설정 추가
  docker-compose.yml
Labels: enhancement

#18 [feat] cors 설정, swagger 개발 환경 추가 및 JwtFilter 클래스 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SwaggerConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/WebMvcConfig.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
Labels: enhancement

#22 [feat] UrlType 클래스 수정 및 WebMvgConfig 클래스 프론트 local 주소 요청 허용 설정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/WebMvcConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
Labels: enhancement

#19 [feat] 닉네임 중복 검증 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/controller/AuthControllerTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
Labels: enhancement

#25 [refactor] 닉네임 검증 메서드 응답값 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/controller/AuthControllerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
Labels: refactor

#26 Refactor/#23/OAauth2 kakao
  docker-compose.yml
  sport_companion/module-api/build.gradle
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/ApiApplication.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtUtil.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/UserHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/utils/HttpCookieUtil.java
  sport_companion/module-api/src/main/resources/application-dev.yml
  sport_companion/module-api/src/main/resources/application-prod.yml
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/UserHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-domain/build.gradle
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/config/RedisConfig.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SignUpDataEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SignUpDataRepository.java
Labels: duplicate

#29 [feat] 모든 구단 조회 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/utils/HttpCookieUtil.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/ClubsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/ReservationSiteEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/clubs/Clubs.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/ReservationSiteRepository.java
Labels: enhancement

#30 [feat] ArgumentResolver로 API 요청 사용자 정보 조회 기능 추가
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/CallUserResolver.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/WebMvcConfig.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/annotation/CallUser.java
Labels: enhancement

#32 [feat] 뉴스 크롤링 배치 작업 추가
  sport_companion/module-batch/build.gradle
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/component/BatchScheduler.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/component/WebDriverHandler.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/config/BatchConfig.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/MbcNewsCrawling.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/NewsItemWriter.java
  sport_companion/module-batch/src/main/resources/application-dev.yml
  sport_companion/module-batch/src/main/resources/application.yml
  sport_companion/module-batch/src/test/java/com/service/sport_companion/batch/news/MbcNewsCrawlingTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/NewsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/NewsType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/NewsRepository.java
Labels: enhancement

#35 [feat] Jwt Access 토큰 재발급 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
Labels: enhancement

#37 [fix] 카카오 회원가입 및 로그인 요청 응답 전달 방식 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/auth/SignUpData.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
Labels: fix

#39 [fix] 모든 구단 조회시 전달 데이터 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/ClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/ClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/clubs/Clubs.java
Labels: fix

#47 [refactor] SecurityConfig 클래스 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/auth/KakaoCode.java
Labels: refactor

#49 [refactor] DTO 클래스 Json 파싱 어노테이션 추가
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/auth/KakaoCode.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/auth/KakaoCodeDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/auth/SignUpDto.java
Labels: refactor

#42 [fix] 뉴스 링크 저장 형식 절대 경로로 수정
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/news/MbcNewsCrawling.java
  sport_companion/module-batch/src/test/java/com/service/sport_companion/batch/news/MbcNewsCrawlingTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/UrlType.java
Labels: fix

#43 [feat] 뉴스 조회 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/NewsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/NewsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/NewsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/NewsServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/controller/NewsControllerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/NewsServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/PageResponse.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/news/NewsResponseDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/NewsRepository.java
Labels: enhancement

#51 [refactor] ResultResponse의 data를 제너릭 타입으로 수정
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/ClubsController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/ClubsService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/AuthServiceImpl.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/ClubsServiceImpl.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/response/ResultResponse.java
Labels: refactor

#52 [feat] 주제(CustomTopic) 생성 및 삭제 API 구현
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/CustomTopicHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/CustomTopicController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/CustomTopicService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/CustomTopicServiceImplTest.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/CustomTopicEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/dto/request/topic/CreateTopicDto.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/FailedResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/CustomTopicRepository.java
Labels: enhancement

#54 [feat] 경기 일정 크롤링 API 구현
  sport_companion/module-api/build.gradle
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/auth/jwt/JwtFilter.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/ClubsHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/FixtureHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/SeasonHandler.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/component/crawl/CrawlFixtures.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/config/SecurityConfig.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/AuthController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/controller/FixturesController.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/AuthService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/FixturesService.java
  sport_companion/module-api/src/main/java/com/service/sport_companion/api/service/impl/FixturesServiceImpl.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/ClubsHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/FixtureHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/SeasonHandlerTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/component/crawl/CrawlFixturesTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/AuthServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/ClubsServiceImplTest.java
  sport_companion/module-api/src/test/java/com/service/sport_companion/api/service/impl/FixturesServiceImplTest.java
  sport_companion/module-batch/src/main/java/com/service/sport_companion/batch/config/NewsCrawlConfig.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/FixturesEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/entity/SeasonsEntity.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/model/type/SuccessResultType.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/ClubsRepository.java
  sport_companion/module-domain/src/main/java/com/service/sport_companion/domain/repository/SeasonsRepository.java
Labels: refactor
